repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|h)$
        args: ["-i"]
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        files: \.(c|h)$
        args: ["-p", "build"]
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        files: \.(c|h)$
        args:
          [
            "--enable=all",
            "--inconclusive",
            "--error-exitcode=1",
            "--force",
            "--inline-suppr",
            ".",
          ]
